-- Generated automatically by `./gradlew generateSchemaDocs`
-- from com.negocore.infrastructure.output.jpa.entity.AuditLogEntity on 2026-09-29.
-- Reference documentation only: this file is not run anywhere (not by
-- the app, not by a migration tool) and is not kept in sync automatically.
-- Regenerate after changing this entity.

create table audit_logs (id bigint generated by default as identity, action varchar(60) not null, business_id bigint, created_at timestamp(6) not null, details TEXT, entity varchar(60), entity_id bigint, user_id bigint, primary key (id));
