-- Generated automatically by `./gradlew generateSchemaDocs`
-- from com.negocore.infrastructure.output.jpa.entity.BusinessEntity on 2026-09-29.
-- Reference documentation only: this file is not run anywhere (not by
-- the app, not by a migration tool) and is not kept in sync automatically.
-- Regenerate after changing this entity.

create table businesses (id bigint generated by default as identity, active boolean, address varchar(200), created_at timestamp(6), currency varchar(3), email varchar(150), name varchar(100), owner_id bigint, phone varchar(20), primary key (id));
