-- Generated automatically by `./gradlew generateSchemaDocs`
-- from com.negocore.infrastructure.output.jpa.entity.CategoryEntity on 2026-09-29.
-- Reference documentation only: this file is not run anywhere (not by
-- the app, not by a migration tool) and is not kept in sync automatically.
-- Regenerate after changing this entity.

create table category (id bigint generated by default as identity, active boolean not null, business_id bigint not null, created_at timestamp(6) not null, name varchar(255) not null, primary key (id), constraint uk_category_business_name unique (business_id, name));
