-- Generated automatically by `./gradlew generateSchemaDocs`
-- from com.negocore.infrastructure.output.jpa.entity.ClientEntity on 2026-09-29.
-- Reference documentation only: this file is not run anywhere (not by
-- the app, not by a migration tool) and is not kept in sync automatically.
-- Regenerate after changing this entity.

create table clients (id bigint generated by default as identity, address varchar(200), business_id bigint not null, created_at timestamp(6) not null, email varchar(150), name varchar(100) not null, phone varchar(20), primary key (id));
