-- Generated automatically by `./gradlew generateSchemaDocs`
-- from com.negocore.infrastructure.output.jpa.entity.DebtPaymentEntity on 2026-09-29.
-- Reference documentation only: this file is not run anywhere (not by
-- the app, not by a migration tool) and is not kept in sync automatically.
-- Regenerate after changing this entity.

create table debt_payments (id bigint generated by default as identity, amount numeric(38,2) not null, created_at timestamp(6) not null, debt_id bigint not null, payment_method varchar(255) not null check (payment_method in ('CASH','TRANSFER','CARD')), primary key (id));
