-- Generated automatically by `./gradlew generateSchemaDocs`
-- from com.negocore.infrastructure.output.jpa.entity.DebtEntity on 2026-09-29.
-- Reference documentation only: this file is not run anywhere (not by
-- the app, not by a migration tool) and is not kept in sync automatically.
-- Regenerate after changing this entity.

create table debts (id bigint generated by default as identity, business_id bigint not null, client_id bigint, created_at timestamp(6) not null, debtor_name varchar(100), due_date date, paid_amount numeric(38,2) not null, sale_id bigint, status varchar(255) not null check (status in ('PENDING','PARTIAL','PAID','CANCELLED')), total_amount numeric(38,2) not null, primary key (id));
