-- Generated automatically by `./gradlew generateSchemaDocs`
-- from com.negocore.infrastructure.output.jpa.entity.ExpenseEntity on 2026-09-29.
-- Reference documentation only: this file is not run anywhere (not by
-- the app, not by a migration tool) and is not kept in sync automatically.
-- Regenerate after changing this entity.

create table expenses (id bigint generated by default as identity, amount numeric(38,2) not null, business_id bigint not null, category varchar(60), created_at timestamp(6) not null, description varchar(200) not null, paid boolean default true not null, primary key (id));
