-- Generated automatically by `./gradlew generateSchemaDocs`
-- from com.negocore.infrastructure.output.jpa.entity.OrderEntity on 2026-09-29.
-- Reference documentation only: this file is not run anywhere (not by
-- the app, not by a migration tool) and is not kept in sync automatically.
-- Regenerate after changing this entity.

create table orders (id bigint generated by default as identity, business_id bigint not null, converted_at timestamp(6), converted_purchase_id bigint, created_at timestamp(6) not null, order_number integer not null, status varchar(255) not null check (status in ('OPEN','CONVERTED','CANCELLED')), primary key (id), constraint uk_order_business_number unique (business_id, order_number));
