-- Generated automatically by `./gradlew generateSchemaDocs`
-- from com.negocore.infrastructure.output.jpa.entity.OrderItemEntity on 2026-09-29.
-- Reference documentation only: this file is not run anywhere (not by
-- the app, not by a migration tool) and is not kept in sync automatically.
-- Regenerate after changing this entity.

create table order_items (id bigint generated by default as identity, client_id bigint, converted_sale_id bigint, created_at timestamp(6) not null, order_id bigint not null, product_id bigint not null, quantity integer not null, requester_name varchar(255), sale_price numeric(38,2), unit_cost numeric(38,2), primary key (id));
