-- Generated automatically by `./gradlew generateSchemaDocs`
-- from com.negocore.infrastructure.output.jpa.entity.ProductEntity on 2026-09-29.
-- Reference documentation only: this file is not run anywhere (not by
-- the app, not by a migration tool) and is not kept in sync automatically.
-- Regenerate after changing this entity.

create table products (id bigint generated by default as identity, active boolean, business_id bigint, category_id bigint, cost_price numeric(38,2), created_at timestamp(6), image_url varchar(255), min_stock_alert integer, name varchar(255), sale_price numeric(38,2), sku varchar(255), stock integer, primary key (id), constraint uk_product_business_sku unique (business_id, sku));
