-- Generated automatically by `./gradlew generateSchemaDocs`
-- from com.negocore.infrastructure.output.jpa.entity.PurchaseItemEntity on 2026-09-29.
-- Reference documentation only: this file is not run anywhere (not by
-- the app, not by a migration tool) and is not kept in sync automatically.
-- Regenerate after changing this entity.

create table purchase_items (id bigint generated by default as identity, product_id bigint not null, purchase_id bigint not null, quantity integer not null, subtotal numeric(38,2) not null, unit_cost numeric(38,2) not null, primary key (id));
