-- Generated automatically by `./gradlew generateSchemaDocs`
-- from com.negocore.infrastructure.output.jpa.entity.PurchaseEntity on 2026-09-29.
-- Reference documentation only: this file is not run anywhere (not by
-- the app, not by a migration tool) and is not kept in sync automatically.
-- Regenerate after changing this entity.

create table purchases (id bigint generated by default as identity, business_id bigint not null, created_at timestamp(6) not null, paid_amount numeric(38,2) not null, payment_method varchar(255) not null check (payment_method in ('CASH','TRANSFER','CARD','MIXED')), provider_id bigint not null, shipping_cost numeric(38,2), status varchar(255) not null check (status in ('PAID','PARTIAL','CANCELLED')), total numeric(38,2) not null, primary key (id));
