-- Generated automatically by `./gradlew generateSchemaDocs`
-- from com.negocore.infrastructure.output.jpa.entity.UserEntity on 2026-09-29.
-- Reference documentation only: this file is not run anywhere (not by
-- the app, not by a migration tool) and is not kept in sync automatically.
-- Regenerate after changing this entity.

create table users (id bigint generated by default as identity, active boolean not null, created_at timestamp(6), email varchar(255) unique, name varchar(255), password varchar(255), phone_number varchar(255), primary key (id));
